appenders:
  my_stdout:
    kind: console
    encoder:
      pattern: "{h({d(%H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n})}"
root:
  level: info
  appenders:
    - my_stdout
    - my_file_logger

loggers:
  tracing:
    level: off
